<a href="https://colab.research.google.com/github/rakamaulanaa/Assignment-sesi-2/blob/main/2702371136_Raka_Maulana_Akbar_Regression_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')

x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))

A = np.vstack([x, np.ones(len(x))]).T

y = y[:, np.newaxis]

alpha = np.dot((np.dot(np.linalg.inv(np.dot(A. T, A)),A.T)) ,y)
print(alpha)


[[1.55898941]
 [0.99294784]]


<ipython-input-6-c2f1f7b6d82c>:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-poster')


In [ ]:
pinv = np.linalg.pinv(A)
alpha = pinv.dot(y)
print(alpha)

[[1.55898941]
 [0.99294784]]


In [ ]:
alpha = np.linalg.lstsq(A, y, rcond=None) [0]
print(alpha)

[[1.55898941]
 [0.99294784]]


In [ ]:
x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))

def func(x, a, b):
    y = a*x + b
    return y

alpha = optimize.curve_fit(func, xdata = x, ydata = y) [0]
print(alpha)

[1.52099687 0.97694036]
